spring.application.name=energiai-api


ml.model.service.url=${ML_SERVICE_URL:http://localhost:8000}

fastapi.base-url=${FASTAPI_BASE_URL}
fastapi.api-key=${FASTAPI_KEY}
dias.mes=${DIAS_MES}
precio.kwh=${PRECIO_KWH}